services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - proxy-net

networks:
    proxy-net:
        name: proxy-net
        external: true
